### ISSUE TITLE
2d convolution operator

### ISSUE THREAD

**Issue by 1oly** [kul-forbes/AbstractOperators.jl#11]
Hi,

First of all thanks for putting together this package (and ProximalOperators/Algorithms) - it's really nice to play with and works very well together.

I'm having a difficult time defining an operator for 2d convolution (to be used in basic image deconvolution solved by `LeastSquare`). Normally, I would have something like

```
ifft(fft(psf).*fft(x))
```
instead of `A*x`, where `A` is the 2d convolution matrix (block Toeplitz with Toeplitz Blocks BTTB), and `psf` is the point spread function (forgive me if this is too much irrelevant information). 

I've tried to use `Compose` with 

```
n = 10
A = IDFT(n,n)
B = DFT(n,n)
A = Compose(A,B)
``` 
but this gives a DomainError since `domainType(A) != codomainType(B)`.

Would appreciate any tips you might have, and can also cook up a full MWE if the above is not clear.

Thanks!

**Comment by nantonel** [comment]
Hi! Glad you're happy with these packages! 😄 

The problem you have is that by default `IDFT` and `DFT` assume that the input is a `Float64` array.
However you can change this behaviour using a different constructor:
```julia
using AbstractOperators
n = 10
A = IDFT(Complex{Float64}, (n,n))
PSF = DiagOp(randn(n,n)+im*randn(n,n))
B = DFT(n,n)
C = Compose(A,Compose(PSF,B))
```
notice that the output of `C` is complex. If you want to have a real output there that might be possible by using the `DFT(n,n)'`instead of A and properly scale it (always forget whether is `1/n^2` or `n^2`)! 

By the way in [StructuredOptimization.jl](https://github.com/kul-forbes/StructuredOptimization.jl) all of this should be automatised!

**Comment by 1oly** [comment]
Perfect, thanks! 

And StructuredOptimization.jl solves my next question about constraints 💯
